# Generated by Django 4.0.5 on 2022-07-04 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default=models.DateTimeField(default=django.utils.timezone.now), max_length=100),
        ),
    ]
